lst = ['Cow','Cat','Dog','Kangaroo','Lion']
print(lst)
lst.append('Tiger')
print(lst)
lst.extend(['Owl'])
print(lst)
lst.sort()
print(lst)
lst.pop()
print(lst)
print(lst.index('Dog'))
lst.insert(2,'Carrot')
print(lst)
lst.remove('Dog')
print(lst)